# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [4]:
import numpy as np

In [3]:
my_list = [4,5,6,7,'John',7.0,5]
print(my_list)

[4, 5, 6, 7, 'John', 7.0, 5]


### What is an array ?
Array is a container which can hold a fix number of items and these items should be of the same type.
Each item in an array is identified by its index.
The main difference between these arrays and lists is the kind operation you can perform on them.
Another differnce is that, lists are containers for elements of differing data types but arrays are used as containers for elements of the same data type

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [6]:
evens = [2,4,6,8,10]
evens

[2, 4, 6, 8, 10]

#### Producing one dimentional array

In [12]:
even_array = np.array(evens)
print(even_array)
even_array.shape

[ 2  4  6  8 10]


(5,)

#### Producing two dimesional arrays  / Matrices
A two dimensional array or a matrix can be produced by casting a list of lists

In [8]:
my_matrix = [[1,2,3],
             [4,5,6],
             [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
## range 
emt_arr = []
np.array(emt_arr)


array([], dtype=float64)

## Using  Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
## moving in steps
np.arange(0,11,6)

array([0, 6])

In [19]:
my_arr = np.array([1,2,4,5])

### zeros and ones

Generate arrays of zeros or ones

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [20]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [27]:
np.linspace(0,11,6)

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. ])

In [29]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Creating an Identity Matrix with  eye



In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [31]:
np.random.rand(5)

array([0.40639943, 0.1969459 , 0.76447755, 0.26973104, 0.74906996])

In [33]:
np.random.rand(4,4)

array([[0.36634388, 0.22585076, 0.77455494, 0.07060894],
       [0.24966636, 0.91919534, 0.47779524, 0.58810021],
       [0.52260808, 0.27640218, 0.66190844, 0.29300954],
       [0.72670824, 0.89497533, 0.14408579, 0.10974404]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [48]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [45]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [36]:
np.random.randint(1,1000)

958

In [39]:
np.random.randint(1,1000,38)

array([211, 309, 534, 800, 141, 545, 303, 274, 554, 453, 990, 697, 340,
       961, 665, 377,  74, 305, 358, 462, 434, 336, 440, 132, 727, 360,
       168, 256, 990, 320, 135, 496, 987,  38, 503, 628, 661, 932])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [40]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape
Returns an array containing the same data with a new shape.

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
# 16  = 2*2*2*2
# 15 = 5*3 = 3*5
# 24 = 24*1 = 12*2 = 4*6 = 6*4 = 8*3 = 3*8 = 2*12
my_arr = np.arange(72)
wilfred = my_arr.reshape(36,2)
bryte = my_arr.reshape(6,12)
joseph = my_arr.reshape(8,9)
joshua = my_arr.reshape(18,4)
seyram = my_arr.reshape(24,3)

print(wilfred)
print(bryte)
print(joseph)
print(joshua)
print(seyram)


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]
 [50 51]
 [52 53]
 [54 55]
 [56 57]
 [58 59]
 [60 61]
 [62 63]
 [64 65]
 [66 67]
 [68 69]
 [70 71]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71]]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [64]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [61]:
ranarr.max()

49

In [62]:
ranarr.argmax()

4

In [63]:
ranarr.min()

2

In [60]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [65]:
# Vector
arr.shape

(25,)

In [66]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

dtype('int64')

# Great Job!